version: '3.8'

services:
    app:
        image: best-cost-route-finder
        depends_on:
        - db
        build:
            context: ./BestCostRouteFinder.API/
            dockerfile: .
        ports:
        - 5000:5000

    db:
        image: sqlserver-db
        build:
            context: ./BestCostRouteFinder.Infrastructure/ExternalServices/Database/SqlServer2019/
            dockerfile: .
        ports:
            - '1433:1433'